### ISSUE TITLE
`index.php`s execution is bad

### ISSUE THREAD

**Issue by philipbrembeck** [JokeNetwork/faq#7]
This should be solved with a javascript framework and not with a vulnerable language like php.

**Comment by gitgauner** [comment]
Here are some measurements we're currently working on as part of our code optimization program:

- Testing framework solutions
- Developing a solution based on js
- Testing a solution based on js

So far, we are not completely satisfied with any solution, as it should be as easy as possible and understandable for everyone, since the idea of this repo is for everyone to contribute, without having to learn our specific code.

**Comment by philipbrembeck** [comment]
+ Added Github API in PHP for now

**Comment by philipbrembeck** [comment]
We discussed this quite a while now and while we know of the benefits of a interactive javascript framework, we don't think php is outdated or will be anytime soon.

We researched different solutions, such as Gridsome for Vue, since we were looking for static pages.

As of now, we're pretty sure that PHP combined with HTML and a bit of JavaScript is enough for this little project.

If anyone is interested in researching this further, please do so and open a pull request. 

We'll focus on code cleanup and code review, as well as adding ˋalpine.jsˋ for some flexibility   in the meantime, instead of creating everything new from scratch.

Closed.
